#!/bin/bash

set -eux

MEM_PER_CPU="4000M"
CORES_PER_TASK="32"
EXCLUSIVE=1

EXCLUSIVE_STR="--exclusive"
if [ $EXCLUSIVE == 0 ]; then
	EXCLUSIVE_STR=""
fi

HELPSTR="\
Usage:\n\
run_single_bench <proving_keys_bin> <num_worker_cores> \
"

if [ -z ${1+x} ] || [ -z ${2+x} ]; then
    echo -e "$HELPSTR"
    exit 1
fi

KEYFILE_PATH=$1
NUM_WORKER_CORES=$2
NUM_WORKER_TASKS=$(($NUM_WORKER_CORES / $CORES_PER_TASK))

JOB_DESC=$(basename $KEYFILE_PATH | cut -d- -f2-3 | cut -d. -f1)

DATETIME=$(printf '%(%Y%m%d.%H%M%S)T\n' -1)
OUT_FILENAME="bench_out-${JOB_DESC}-${DATETIME}.txt"
ERR_FILENAME="bench_err-${JOB_DESC}-${DATETIME}.txt"

sbatch \
	--wait \
	--time 12:00:00 \
	--account imiers-prj-cmsc \
	--job-name $JOB_DESC \
       	--out=$OUT_FILENAME \
	--error=$ERR_FILENAME \
	--ntasks=$(($NUM_WORKER_TASKS + 1)) \
	--mem-per-cpu=$MEM_PER_CPU \
	--cpus-per-task=$(($CORES_PER_TASK + 1)) \
	$EXCLUSIVE_STR \
	./bench_job.slurm $KEYFILE_PATH $NUM_WORKER_TASKS $(($CORES_PER_TASK + 1))

#srun \
#	--time 20:00 \
#	--account imiers-prj-cmsc \
#	--job-name $JOB_DESC \
#       	--out=$OUT_FILENAME \
#	--error=$ERR_FILENAME \
#	--ntasks=1 \
#	--mem-per-cpu=$MEM_PER_CPU \
#	--cpus-per-task=$CPUS_FOR_COORDINATOR \
#	./bench_job.slurm $KEYFILE_PATH $NUM_WORKERS $CORES_PER_TASK
#	: \
#       	--out="$OUT_FILENAME-2" \
#	--error="$ERR_FILENAME-2" \
#	--ntasks=$NUM_WORKERS \
#	--mem-per-cpu=$MEM_PER_CPU \
#	--cpus-per-task=$CORES_PER_TASK \
#	./bench_job $KEYFILE_PATH $NUM_WORKERS $CORES_PER_TASK


#srun --time 20:00 --account imiers-prj-cmsc --partition=standard --job-name $JOB_DESC \
#	--out=$OUT_FILENAME --error=$ERR_FILENAME \
#	--ntasks=1 --mem-per-cpu=$MEM_PER_CPU --cpus-per-task=$CPUS_FOR_COORDINATOR \
#	./bench_job.slurm $KEYFILE_PATH $NUM_WORKERS $CORES_PER_TASK : \
#       	--ntasks=$NUM_WORKERS --mem-per-cpu=$MEM_PER_CPU --cpus-per-task=$CORES_PER_TASK \
#	./bench_job.slurm $KEYFILE_PATH $NUM_WORKERS $CORES_PER_TASK $CPUS_FOR_COORDINATOR

echo "JOB DESC: ${JOB_DESC}" >> $OUT_FILENAME
echo "NUM WORKER TASKS: ${NUM_WORKER_TASKS}" >> $OUT_FILENAME
echo "MEM PER CORE: ${MEM_PER_CPU}" >> $OUT_FILENAME
echo "CORES PER TASK: ${CORES_PER_TASK}" >> $OUT_FILENAME
echo "${@:0}" >> $OUT_FILENAME

if [ $EXCLUSIVE == 1 ]; then
	echo "EXCLUSIVE: true" >> $OUT_FILENAME
else
	echo "EXCLUSIVE: false" >> $OUT_FILENAME
fi
